# tbuserkb
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  ga_tracker: 'UA-XXXXXX-X'
  admin_email: admin@example.com
  google_maps_api_key: AIzaSyCFKDd9ikVYoOPCl0zgd9Xaf8K4MonwlN4
  secret_key_base: ff0e29d4b5ffbe7133b923726baf0d36c23e912a8c9984c95e3842c64abc38bddc8baabcbd0c0a2dbaf9e40fe21e53efe6476107a9ef023fef75ff4c774362d4
  companies_redis_path: 'redis://127.0.0.1:6379/0'
  host: app.local
  no_reply_email: 'no-reply@fairpard.com'
  parser:
    alibaba_connection: 'mongodb://127.0.0.1:27017/fairpard_parser_alibaba_development'
  bing:
    name: fairpard-staging
    first_key: abc123
    second_key: abc123
  oauth:
    vkontakte:
      api_key: 5735966
      api_secret: 1BkTIXWyqa88Owq37Xv2
    facebook:
      api_key: 1811573835756753
      api_secret: 740f2db3bbcdc709a3081beab5631095
    twitter:
      api_key: F8eKThF9YQFN07QxHVAnpTtBs
      api_secret: MRP6YCw3tr6ADofEq6345CHgBtwSm8AOaqMTttTGVFtQ6Qn5bl

test:
  ga_tracker: 'UA-XXXXXX-X'
  google_maps_api_key: AIzaSyCFKDd9ikVYoOPCl0zgd9Xaf8K4MonwlN4
  secret_key_base: cd853313a411f41baa9f68b75b71737defa8671eb07037eee49b3d42a5dfe2b0eae4c393b4f9cc9357ebdac8f5aae30923e82ac4653b6bd47b116809c54a7092
  companies_redis_path: 'redis://127.0.0.1:6379/0'
  alibaba_suppliers_mongo_database: 'alibaba_suppliers_test'
  host: app.test
  no_reply_email: 'no-reply@fairpard.com'
  parser:
    alibaba_connection: 'mongodb://127.0.0.1:27017/fairpard_parser_alibaba_test'
  bing:
    name: name
    first_key: first_key
    second_key: second_key
  oauth:
    vkontakte:
      api_key: 5735966
      api_secret: 1BkTIXWyqa88Owq37Xv2
    facebook:
      api_key: 1811573835756753
      api_secret: 740f2db3bbcdc709a3081beab5631095
    twitter:
      api_key: zLP1IbH66Qb4x2J7atHDLer2P
      api_secret: 85ZBu1aCNLAc0AlaLkOzUIbYxir0t8ZVOc0w2iu6FmB0MlxPFT


ci:
  ga_tracker: <%= ENV["GA_TRACKER"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  companies_redis_path: <%= ENV["COMPANIES_REDIS_PATH"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  host: test.host
  no_reply_email: 'no-reply@fairpard.com'
  parser:
    alibaba_connection: 'mongodb://127.0.0.1:27017/fairpard_parser_alibaba_test'
  bing:
    name: <%= ENV['BING_NAME'] %>
    first_key: <%= ENV['BING_FIRST_KEY'] %>
    second_key: <%= ENV['BING_SECOND_KEY'] %>
  oauth:
    vkontakte:
      api_key: <%= ENV["OAUTH_VKONTAKTE_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_VKONTAKTE_API_SECRET"] %>
    facebook:
      api_key: <%= ENV["OAUTH_FACEBOOK_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_FACEBOOK_API_SECRET"] %>
    twitter:
      api_key: <%= ENV["OAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_TWITTER_API_SECRET"] %>

staging:
  ga_tracker: <%= ENV["GA_TRACKER"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  companies_redis_path: <%= ENV["COMPANIES_REDIS_PATH"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  host: <%= ENV["HOST"] %>
  no_reply_email: <%= ENV['NO_REPLY_EMAIL'] %>
  parser:
    alibaba_connection: 'mongodb://127.0.0.1:27017/fairpard_parser_alibaba_development'
  bing:
    name: <%= ENV['BING_NAME'] %>
    first_key: <%= ENV['BING_FIRST_KEY'] %>
    second_key: <%= ENV['BING_SECOND_KEY'] %>
  oauth:
    vkontakte:
      api_key: <%= ENV["OAUTH_VKONTAKTE_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_VKONTAKTE_API_SECRET"] %>
    facebook:
      api_key: <%= ENV["OAUTH_FACEBOOK_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_FACEBOOK_API_SECRET"] %>
    twitter:
      api_key: <%= ENV["OAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_TWITTER_API_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  ga_tracker: <%= ENV["GA_TRACKER"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  companies_redis_path: <%= ENV["COMPANIES_REDIS_PATH"] %>
  host: <%= ENV["HOST"] %>
  no_reply_email: <%= ENV['NO_REPLY_EMAIL'] %>
  parser:
    alibaba_connection: 'mongodb://127.0.0.1:27017/fairpard_parser_alibaba_development'
  bing:
    name: <%= ENV['BING_NAME'] %>
    first_key: <%= ENV['BING_FIRST_KEY'] %>
    second_key: <%= ENV['BING_SECOND_KEY'] %>
  oauth:
    vkontakte:
      api_key: <%= ENV["OAUTH_VKONTAKTE_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_VKONTAKTE_API_SECRET"] %>
    facebook:
      api_key: <%= ENV["OAUTH_FACEBOOK_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_FACEBOOK_API_SECRET"] %>
    twitter:
      api_key: <%= ENV["OAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OAUTH_TWITTER_API_SECRET"] %>
